# Generated by Django 4.2 on 2025-08-10 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='code',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
