# Generated by Django 4.2 on 2025-08-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='core_commen_post_id_0d7c44_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailverification',
            name='core_emailv_code_46b072_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailverification',
            name='core_emailv_token_606d0a_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='core_post_user_id_104131_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='core_post_created_2da706_idx',
        ),
        migrations.RemoveIndex(
            model_name='postreact',
            name='core_postre_post_id_8e45a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='postreact',
            name='core_postre_user_id_0f392f_idx',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='code',
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
