# Generated by Django 4.2 on 2025-08-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
